import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Provider from '@/common/components/Provider';
import Navbar from '@/common/components/Navbar';
import ClientWrapper from '@/common/components/ClientWrapper';
import Modal from '@/common/components/Modal';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className='h-full overflow-hidden flex flex-col'>
        <Provider>
          <ClientWrapper>{children}</ClientWrapper>
        </Provider>
      </body>
    </html>
  );
}
